### PR TITLE
Add Svelte support

### PR DESCRIPTION
**Pull request by rassie**
Requires https://github.com/lassik/emacs-language-id/pull/7.

### CODE REVIEW

**Comment by lassik** [comment]
Thanks. Please also add Svelte to the following places:

- Language listing in `README.md`.
- Language listing in `Commentary:` section at the top of the `.el` file.
- In `(define-format-all-formatter prettier ...)` in the `(:languages ...)` list.

I.e. everywhere prettier is mentioned.

**Comment by lassik** [comment]
Svelte doesn't seem to be in the default list of languages supported by Prettier. Does this require [prettier-plugin-svelte](https://github.com/sveltejs/prettier-plugin-svelte)?

**Comment by rassie** [comment]
> Svelte doesn't seem to be in the default list of languages supported by Prettier. Does this require [prettier-plugin-svelte](https://github.com/sveltejs/prettier-plugin-svelte)?

Yes, it does. AFAIK, `prettier-plugin-svelte` gets installed automatically for every new Svelte/Svelte.Kit project. Does this change the implementation in some way?

**Comment by rassie** [comment]
> Thanks. Please also add Svelte to the following places:
> 
> * Language listing in `README.md`.
> * Language listing in `Commentary:` section at the top of the `.el` file.
> * In `(define-format-all-formatter prettier ...)` in the `(:languages ...)` list.
> 
> I.e. everywhere prettier is mentioned.

I think I have covered all the bases now, including increasing `language-id` dependency version. Thanks!

**Comment by lassik** [comment]
> Yes, it does. AFAIK, `prettier-plugin-svelte` gets installed automatically for every new Svelte/Svelte.Kit project. Does this change the implementation in some way?

No, the current PR is fine. The install commands in format-all are never run automatically, they're just shown as a hint to the user when a formatter executable is not found.

> I think I have covered all the bases now, including increasing `language-id` dependency version.

Good call! Everything looks good to me. MELPA should autobuild it within 1-2 hours.

**Comment by rassie** [comment]
Thanks for the quick merge!

**Pull request merged**
