### PR TITLE
Define formatter for nix files

### PR DESCRIPTION
**Pull request by jmorag**

### CODE REVIEW

**Comment by lassik** [comment]
Thank you. You appear to have an old version of format-all; `format-all-buffer-easy` is now spelled `format-all--buffer-easy` with two dashes in the middle? With that change, it works. Please re-commit your work with that change on top of the current master I'll merge it then.

**Comment by lassik** [comment]
Please also add nixfmt to the formatter lists:

* in the comment at the top of format-all.el
* in README.md

Both lists are in alphabetical order. Please copy the text formatting from the other formatters :)

**Comment by jmorag** [comment]
Done! Thanks for the quick response :)

**Comment by lassik** [comment]
Merged. You too!

**Comment by lassik** [comment]
MELPA should pick it up in a few hours.

**Pull request merged**
