### PR TITLE
Added example using use-package

### PR DESCRIPTION
**Pull request by o0nd7ots**
I am sharing what I have learned

### CODE REVIEW

**Comment by o0nd7ots** [comment]
I hope this will make it easier for new users to start taking advantage of this wonderful tool.

**Comment by lassik** [comment]
Thank you! It's nice to have help with the README.

**Comment by o0nd7ots** [comment]
I am happy to help! I like contributing to FOSS projects that I use.

By the way, when you have could you please explain why did you choose the MIT license for this project?

**Comment by lassik** [comment]
Simplicity.

**Pull request merged**
