### PR TITLE
Define a formatter for SQL (sqlformat)

### PR DESCRIPTION
**Pull request by knu**
It uses sqlformat from the Python package "sqlparse" with some options of choice:

- `-k upper`: to uppercase keywords
- `-a`: to get a multiline, aligned output

### CODE REVIEW

**Comment by knu** [comment]
Oops, I've removed the superfluous `py-` prefix.

As for encoding, despite [this PR](https://github.com/andialbrecht/sqlparse/pull/316) merged, the sqlformat command does not seem to handle UTF-8 well with Python2, so I recommend you use Python3 for now; sqlformat does not (yet) have an `--encoding` option.

And yes, I still use FreeBSD on my personal server and make commits from time to time. 😁  I code a lot mainly in Ruby/Rails and ECMAScript in the web development scene, although Emacs is no longer very popular there. 😆

**Comment by lassik** [comment]
Thanks for updating the code.

If Python 2 is known to be problematic, we could just change the install command to `pip3 install sqlparse` (note the `3` in `pip3`). Python 3 / PIP 3 ought to be available everywhere nowadays.

I just added a `freebsd` system type for the install commands :) https://github.com/lassik/emacs-format-all-the-code/blob/master/format-all.el#L72

I installed the latest `sqlparse` from `pip` today, and that version of `sqlformat` does have an `--encoding` option:

```
$ sqlformat --version
0.2.4
$ sqlformat --help | grep -i encoding
  --encoding ENCODING   Specify the input encoding (default utf-8)
$ echo ååöÅÄÖ | iconv -f utf-8 -t iso8859-1 | sqlformat --encoding iso-8859-1 -
ååöÅÄÖ
```

Yeah, unfortunately Emacs' GUI framework has needed modernization for 20 years. And font-lock should finally be replaced with a real parsing framework with multi-language support. Young web devs will no longer put up with these things. I hope our venerable editor survives the next decade. MELPA offers a glimmer of hope :)

**Comment by lassik** [comment]
@knu I'm ready to merge this, but what do you think we should do about the `pip3` suggestion and the `--encoding` option in light of my comments above?

**Comment by knu** [comment]
I'm not sure if pip3 is a widely available name for pip for Python3.  I guess `python3 -m pip` would be a better bet, but in that case, you'd have to call sqlformat as `python3 -m sqlparse`.  Maybe we should work out a way to use Python2 for now...

**Comment by lassik** [comment]
If the only problem with Python 2 is the encoding, we could just make it `pip` (which could be either Python 2 or Python 3, depending on the OS) and leave out the `--encoding` option for now.

**Comment by knu** [comment]
I've finally got it to work with Python 2.7.  I had to set PYTHONIOENCODING for Python <3.2 including 2.7 because the older versions of python wouldn't respect the locale nor default the encoding to UTF-8 when the output is redirected, only to fail in trying to output in ASCII encoding.

**Comment by lassik** [comment]
That's awesome, thank you for the effort :)

Are you sure `ienc` and `oenc` are the right way around? The docstring for `default-process-coding-system` says:

```
The car part is used for decoding a process output,
the cdr part is used for encoding a text to be sent to a process.
```

which seems like they are opposite to the intuitive order. Also, `sqlformat --help` says:

`--encoding ENCODING   Specify the input encoding (default utf-8)`

So that's input too. But what is the output encoding, is it always the same as the input encoding, or does it come from `PYTHONIOENCODING` even if `--encoding` is given`?

Sorry about all this detail...

**Comment by lassik** [comment]
Also, we should probably set envars like:

```
(let ((process-environment (cons (concat "PYTHONIOENCODING=" ienc)
                                 process-environment)))
  (format-all-buffer-process executable ...))
```

instead of depending on the external `env` program.

**Comment by knu** [comment]
Good points, fixed!

**Comment by lassik** [comment]
Looks good to me. Finally merging :) Thanks for your contribution!

**Pull request merged**
