### PR TITLE
Customize error symbol when formatter not found

### PR DESCRIPTION
**Pull request by qoops-1**
That's what I suggested in #140 :)

### CODE REVIEW

**Comment by lassik** [comment]
Thanks!

**Comment by lassik** [comment]
Sorry, the signal's name should probably start with the `format-all-` package prefix, right?

**Comment by lassik** [comment]
`(signal 'format-all-executable-not-found ...)`

**Comment by qoops-1** [comment]
hmm, not sure, but that makes sense

**Pull request merged**
