### PR TITLE
Add ATS

### PR DESCRIPTION
**Pull request by TristanCacqueray**
Depends-On: https://github.com/lassik/emacs-language-id/pull/5

### CODE REVIEW

**Comment by lassik** [comment]
Thanks. Well written patch, and fun to find people who are using ATS!

* Is there a particular reason to use `cabal new-install` instead of just `install`?
* Does the formatter work badly without the custom flags `--happy-options='-gcsa' -O2`?

**Comment by TristanCacqueray** [comment]
This is the command suggested in the ats-format readme: https://github.com/vmchale/ats-format#installation . I guess it would be better to point at that page instead.

**Comment by lassik** [comment]
Nah, if it's the official command it's fine by me. Was just wondering why it's not the usual `cabal install ...` :)

**Comment by TristanCacqueray** [comment]
Alright thank you for the fast review!

- I think cabal>3 install is the new-install, but using new-install ensures the command will work for cabal<2.
- The optimizations flags are probably not required but it seems like they provide a nice performance boost. e.g. Happy options documentation is: https://www.haskell.org/happy/doc/html/sec-invoking.html

**Pull request merged**
