### PR TITLE
Add `ocamlformat` as an OCaml code formatter.

### PR DESCRIPTION
**Pull request by jeongsoolee09**
Hello! I'd like to add `ocamlformat` as a new formatter for OCaml source files.

Thanks for creating this package!

### CODE REVIEW

**Comment by lassik** [comment]
Thanks! Please make the following changes:

* Move the formatter definition in the source file so the definitions are in alphabetical order by formatter name.

* Change `(concat "--name=" (buffer-file-name))` into `(when (buffer-file-name) (concat "--name=" (buffer-file-name)))`. format-all has to be able to format temporary buffers that are not visiting a file. `(buffer-file-name)` returns nil for those buffers.

* Add the new formatter to `README.md` and the big comment on top of `format-all.el`.

**Comment by jeongsoolee09** [comment]
Got it! Should I close this one and open a new PR??

**Comment by lassik** [comment]
Sorry about the long delay. Pushing a new commit to the same PR is ok. I can squash them at the end.

**Comment by lassik** [comment]
Reimplemented as #211; closing this original PR.

**Pull request closed without merging**
